// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

// The schema, the migrations and the seed database all live under
// prisma/schema (see ../../docs/dev.md).
const databaseUrl = 'file:./prisma/schema/data.db'

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/schema/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
})
